name: CI-IPU

on:
  pull_request:
    branches:
      - "**ipu**"
      - "**poptorch**"
  workflow_dispatch:

concurrency:
  # Run everything on main, most-recent on PR builds
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci-ipu:
    runs-on: ubuntu-latest
    container: graphcore/pytorch:3.2.0-ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git
          pip install -r requirements-dev-ipu.txt
      - name: Run CI
        run: ./dev ci
      - name: Publish documentation
        if: ${{github.ref == 'refs/heads/main'}}
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env: { GITHUB_TOKEN: "${{ github.token }}" }
        with:
          build_dir: docs/_build/html
